# CopperComposite v0.2.1 — Frozen (bi-weekly + pnl_net, T+1 VT), 2025-10-10

assumptions:
  oos_start: 2018-01-01
  combine:
    scheme: equal_weight_returns
  scaling:
    mode: tplus1_vt
    target_ann_vol: 10.0       # percent
    vt_lookback_days: 21
    leverage_cap: 2.5

inputs:
  hookcore:
    sleeve: HookCore
    version: 0.4.0
    path: outputs/copper/pricing/daily_series.csv
    fields:
      ret_weekly: return_weekly
      ret_biweekly: return_biweekly
    use_stream: ret_biweekly

  stockscore:
    sleeve: StocksCore
    version: 0.1.1
    path: outputs/copper/stocks/daily_series.csv
    fields:
      ret_gross: ret
      ret_net: pnl_net
    use_field: ret_net

reporting:
  write:
    dir: outputs/copper/composite_ad_hoc
    daily_series: daily_series.csv
    daily_combo: daily_combo.csv
    summary: summary_metrics.csv
