# TrendCore-Cu-v1-Tclose — Static (real-world)
meta:
  name: TrendCore-Cu-v1-Tclose
  instrument: COPPER
  notes: |
    Mon/Wed rebalance (Fri/Tue origin), trade on same-day close (T);
    10% vol-target (21d), sizing uses data up to T, cap 2.5x;
    costs 1.5 bps per |Δposition| on trade days; simple-return PnL.

costs:
  cost_bps_per_turnover: 1.5

signals:
  threshold: 0.85
  z_std_lb: 252

execution:
  vol_lookback_days: 28
  vol_cap: 2.5
  ann_target: 0.10  # informational
  fill_timing: close_T  # (doc hint)
