# ==========================================================
#  HookCore v0.4.0 — Copper Pricing Sleeve
#  Location: docs/copper/pricing/hookcore_config.yaml
#  Purpose:  Defines parameters for the HookCore mean-reversion sleeve
# ==========================================================

sleeve:
  name: "HookCore"
  version: 0.4.0
  description: "Pure mean-reversion sleeve (3d/5d hook, equal-weight blend)"
  status: "frozen"
  created: "2025-10-07"

data:
  source: "copper_lme_3mo"
  frequency: "daily"

signal:
  type: "discrete_hook"
  lookbacks: [3, 5]
  z_threshold: 0.75
  combination: "equal_weight"
  weighting: "discrete ±1 / 0"
  comments: "Long when returns are oversold (z ≤ -0.75), short when overbought (z ≥ +0.75)."

execution:
  schedule: "biweekly"
  rebalance_days: ["Monday", "Wednesday"]
  signal_lag: 1          # T+1 execution
  cost_bps: 1.5
  vol_target:
    annual: 0.10
    lookback: 21
    cap: 2.5

training_window:
  in_sample: ["2008-01-01", "2017-12-31"]
  out_of_sample: ["2018-01-01", "present"]

performance_summary:
  is_sharpe: 0.60
  oos_sharpe: 0.50
  is_ret_pa: 0.105
  oos_ret_pa: 0.080
  is_mdd: -0.15
  oos_mdd: -0.15
  turnover_pa: 6.5
  participation: 0.30

notes: >
  Simple, interpretable mean-reversion sleeve.
  Designed for combination with slower trend and fundamental sleeves.
  Performs best in range-bound or volatile conditions.
  Underperforms in sustained macro trends.
