schema_version: 1
sleeve: TrendImpulse
version: "1.0"
symbol: COPPER
role: tactical_fast_trend
weight_default: 0.30   # suggested blend weight when you composite

inputs:
  excel: "C:\\Code\\Metals\\Data\\copper\\pricing\\pricing_values.xlsx"
  sheet: "Raw"
  date_col: "Date"
  price_col: "copper_lme_3mo"

run:
  cadence: "tuefri"          # <- locked for copper
  z_th: 1.0
  hold: 3
  rebalance_threshold: 0.10
  vol_lookback: 28
  lev_cap: 2.5
  bps: 1.5
  oos_start: "2018-01-01"
  cooldown: 0
  target_vol: 0.10           # (duplicated here for visibility)

outputs:
  root: "outputs/trendimpulse/${symbol}"
  timestamped_runs: true
  write_latest: true
  artifacts:
    - "daily_series.csv"
    - "equity_curves.csv"
    - "summary_metrics.json"
    - "run_lock.json"

metrics_of_interest:
  - sharpe
  - max_dd
  - turnover
  - trades
  - avg_hold
  - hit
  - pct_days_in_pos

# Your composite runner can render this with simple string substitution/Jinja.
# It’s intentionally explicit so other team members (or CI) can run it verbatim.
command_template: >
  .\\.venv\\Scripts\\python.exe src\\build_trendimpulse.py
  --excel "{{inputs.excel}}" --sheet "{{inputs.sheet}}"
  --date-col "{{inputs.date_col}}" --price-col "{{inputs.price_col}}"
  --symbol "{{symbol}}"
  --oos-start "{{run.oos_start}}"
  --z-th {{run.z_th}} --hold {{run.hold}}
  --rebalance-threshold {{run.rebalance_threshold}}
  --vol-lookback {{run.vol_lookback}} --lev-cap {{run.lev_cap}}
  --bps {{run.bps}} --cadence {{run.cadence}} --cooldown {{run.cooldown}}
