execution:
  calendar:
    exec_weekdays: [0, 2, 4]      # Mon, Wed, Fri (project default)
    origin_for_exec:
      "0": "-3B"                  # Monday uses Friday data
      "2": "-1B"                  # Wednesday uses Tuesday data
      "4": "-1B"                  # Friday uses Thursday data
    fill_default: close_T         # signals formed on T close
    pnl_starts_next_day: true     # positions effective next day (T+1)

  sizing:
    ann_target: 0.10
    vol_lookback_days_default: 21
    vol_estimator: simple_returns_std
    vol_info_timing_default: T
    leverage_cap_default: 2.5
    hold_between_rebalances: true

  costs:
    one_way_bps_default: 1.5
    apply_on_position_change_only: true

  pnl:
    formula: pos_lag_times_simple_return
