# Global WFV config (Metals models 2.0)

tier: tierA

data:
  copper:
    tierA:
      price:
        path: "C:\\Code\\Metals\\Data\\copper\\pricing\\pricing_values.xlsx"
        sheet: "Raw"
        date_col: "Date"
        price_col: "copper_lme_3mo"
      stocks:  # optional; kept defined but OFF by default
        path: "C:\\Code\\Metals\\Data\\copper\\stocks\\pricing_stocks_values.xlsx"
        sheet: "Sheet1"
        date_col: "Date"
        stocks_col: "copper_lme_stocks_total"

folds:
  start: "2008-01-01"
  # end:   (default: latest available date)
  train_years: 5
  test_years: 1
  embargo_days: 21   # set 0 in sleeve for parity runs

execution:
  vol_target_annual: 0.10
  vol_cap: 2.5
  vol_lookback_days: 21
  position_clip: 2.5    # DO NOT set below vol_cap; positions only change on exec days
  # execution cadence (fixed in code): Mon & Wed, T+1 fills

costs:
  turn_bps: 1.5         # per |Î”position|; only on exec days (positions change only there)

metrics:
  selection:
    primary: composite
    composite:
      sharpe_weight: 1.0
      dd_penalty_weight: 0.30
      turnover_penalty_weight: 0.10
      tail_bonus_weight: 0.0

# Parameter grids for optimisation (fixed for parity in sleeve)
grids:
  threshold: [0.55, 0.65, 0.75, 0.85, 0.95]
  w35: [0.25, 0.50, 0.75]

search_mode:
  strategy: "coarse_then_local"   # (coarse only is fine too)
  max_total_combos: 120

optimise: false
emit_stitched_oos: true
