version: "Copper StocksCore v0.1.1"
sleeve: "stocks_core"
asof: "latest"

inputs:
  # LME stocks Excel (as provided)
  file: "data/copper/stocks/pricing_stocks_values.xlsx"
  sheet: "Sheet1"                # your file uses Sheet1
  date_col: "Date"
  fields:
    total: "copper_lme_stocks_total"
    onwarrant: "copper_lme_stocks_onwarrant"
    cancelled: "copper_lme_stocks_cancelled"

price:
  table: "prices"                # SQLite table with dt, symbol, px_settle
  symbol: "copper_lme_3mo"       # LME 3M price used for vol targeting & PnL

calendar:
  execution: "T+1"
  trade_days: "daily"

signals:
  # v0.1.1 params
  components:
    - name: "inv_change_20d"
      base: "d_total"
      transform: "zscore"
      lookback: 20
      direction: -1             # negative change (draws) is bullish
      threshold: 1.0
      discrete: true
  combine:
    method: "equal_weight"      # single component; keep for consistency
    cap_abs: 1

features:
  compute:
    onwarrant_pct: "onwarrant / total"
    cancelled_ratio: "cancelled / total"
    d_total: "total - total.shift(1)"

risk:
  vol_target:
    annual: 0.10
    lookback_days: 21
    leverage_cap: 2.5
  costs:
    turnover_bps: 1.5

sample:
  in_sample_start: "2008-01-01"
  in_sample_end:   "2017-12-31"
  out_of_sample_start: "2018-01-01"
  out_of_sample_end:   "latest"

outputs:
  root: "outputs/copper/stocks/stockscore_v0_1_1"
  artifacts:
    - "daily_series.csv"
    - "equity_curves.csv"
    - "summary_metrics.csv"
    - "annual_returns.csv"
